Update

diff --git a/Jenkinsfile_stage_condition b/Jenkinsfile_stage_condition
--- a/Jenkinsfile_stage_condition
+++ b/Jenkinsfile_stage_condition
@@ -12,34 +12,40 @@ pipeline {
 
         stage('TEST') {
             steps {
-                try {
-                    echo "Running the test cases"
-                    sh 'sleep 5'
-                    sh 'exit 1'
-                } catch (Exception e) {
-                    echo "Got an exception, need to handle it."
-                    echo "$e"
-                    testStatus = false
+                script {
+                    try {
+                        echo "Running the test cases"
+                        sh 'sleep 5'
+                        sh 'exit 1'
+                    } catch (Exception e) {
+                        echo "Got an exception, need to handle it."
+                        echo "$e"
+                        testStatus = false
+                    }
                 }
             }
         }
 
         stage('DEPLOY') {
             steps {
-                if (testStatus == true) {
-                    echo "Deploy the app to server"
-                } else {
-                    echo "Skipping Deployment"
+                script {
+                    if (testStatus == true) {
+                        echo "Deploy the app to server"
+                    } else {
+                        echo "Skipping Deployment"
+                    }
                 }
             }
         }
 
         stage('NOTIFICATION') {
             steps {
-                if (testStatus == false) {
-                    echo "Notify the test failure"
-                } else {
-                    echo "Skipping Notification"
+                script {
+                    if (testStatus == false) {
+                        echo "Notify the test failure"
+                    } else {
+                        echo "Skipping Notification"
+                    }
                 }
             }
         }
